StudentTracker/StudentTracker.Web/Controllers/Api/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentTracker.Model;
using StudentTracker.Web.Repositories;

namespace StudentTracker.Web.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class ProfessorController : ControllerBase
    {
        private readonly IProfessorRepository _professorRepository;
        
        public ProfessorController(IProfessorRepository professorRepository)
        {
            _professorRepository = professorRepository;
        }
        
        /// <summary>
        /// Get all professors.
        /// </summary>
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<IEnumerable<Professor>>> GetAll()
        {
            var professors = await _professorRepository.GetAllApi();
            
            return professors.Any() ?
                Ok(professors) :
                NotFound();
        }
        
        /// <summary>
        /// Return a single professor by id.
        /// </summary>
        [HttpGet("{id:guid}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<Professor>> GetProfessorById(Guid id)
        {
            var professorById = (await _professorRepository.GetAllApi())
                .SingleOrDefault(professor => professor.ProfessorId == id);

            return professorById != default ?
                Ok(professorById) :
                NotFound();
        }
    }
}

StudentTracker/StudentTracker.Web/Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using StudentTracker.Web.Repositories;

namespace StudentTracker.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ProfessorController : Controller
    {
        private readonly IProfessorRepository _professorRepository;

        public ProfessorController(IProfessorRepository professorRepository)
        {
            _professorRepository = professorRepository;
        }

        // TODO: Add auth and stop using a random professor.
        public async Task<IActionResult> Index()
        {
            var userProfile = (await _professorRepository.GetAll()).FirstOrDefault();

            return View(userProfile);
        }

        [HttpPost]
        public async Task<IActionResult> GetForm(Guid id)
        {
            var userProfile = (await _professorRepository.GetAll())
                .Single(professor => professor.ProfessorId == id);

            return PartialView("_EditUser", userProfile);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(Guid id)
        {
            var userProfile = (await _professorRepository.GetAll())
                .Single(professor => professor.ProfessorId == id);
            var updateSuccess = await TryUpdateModelAsync(userProfile);

            if (updateSuccess && ModelState.IsValid)
                await _professorRepository.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

StudentTracker/StudentTracker.Web/Views/Professor/Index.cshtml
@model StudentTracker.Model.Professor

<h1>Dashboard</h1>
<hr/>
<h4>Welcome professor @Model.FullName!</h4>

<div>
    <a class="btn btn-primary" id="edit" href="" data-toggle="modal" data-target="#contact-modal">Account settings</a>
</div>

<form asp-action="EditUser" method="POST">
    <div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit account</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div id="EditUserContainer"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Apply changes!</button>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    <script>
        $("#edit").on("click", function () {
            $.ajax({
                url: "@Url.Action("GetForm", "Professor")",
                method: "POST",
                data: {Id : '@Model.ProfessorId'},
                success: function (html) {
                    $("#EditUserContainer").html(html);
                    console.log(html)
                }
            })
        })
    </script>
}

StudentTracker/StudentTracker.Web/Views/Professor/_EditUser.cshtml
@model StudentTracker.Model.Professor

<input type="hidden" id="id" name="id" value="@Model.ProfessorId"/>
<input type="hidden" asp-for="ProfessorId"/>

<div class="form-group">
    <label class="control-label">Full name</label>
    <input asp-for="FullName" type="text" class="form-control"/>
    <span asp-validation-for="FullName" class="text-danger"></span>
</div>

<div class="form-group">
    <label class="control-label">Address</label>
    <input asp-for="Address" type="text" class="form-control"/>
    <span asp-validation-for="Address" class="text-danger"></span>
</div>

<div class="form-group">
    <label class="control-label">Phone</label>
    <input asp-for="Phone" type="text" class="form-control"/>
    <span asp-validation-for="Phone" class="text-danger"></span>
</div>

<partial name="_ValidationScriptsPartial"/>