StudentTracker/StudentTracker.Web/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using StudentTracker.Web.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Text.Json;
using StudentTracker.Model;

namespace StudentTracker.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ClassController : Controller
    {
        private readonly IClassRepository _classRepository;
        private readonly IStudentRepository _studentRepository;

        public ClassController(IClassRepository classRepository, IStudentRepository studentRepository)
        {
            _classRepository = classRepository;
            _studentRepository = studentRepository;
        }

        // TODO: Add auth and stop using a random professor.
        [HttpGet("/user/classes")]
        public async Task<IActionResult> Index(Guid professorId)
        {
            var userClass = (await _classRepository.GetAllClassStudents())
                .Where(c => c.ProfessorId == professorId)
                .ToList();

            ViewBag.professorId = professorId;

            return View(userClass);
        }

        [HttpGet("/user/classes/edit")]
        public async Task<IActionResult> EditClass(Guid classId)
        {
            var userClass = await _classRepository.GetClass(classId);

            await FillDropdownValues(userClass);

            return View(userClass);
        }

        [HttpGet("user/classes/add")]
        public async Task<IActionResult> AddClass(Guid professorId)
        {
            await FillDropdownValues();

            ViewBag.professorId = professorId;

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DeleteClass(Guid classId)
        {
            var deleteClass = await _classRepository.GetClass(classId);

            await _classRepository.DeleteClass(deleteClass);

            return RedirectToAction("Index", new {professorId = deleteClass.ProfessorId});
        }

        [HttpGet]
        private async Task FillDropdownValues(Class userClass = null)
        {
            var selectItems = new List<SelectListItem>
            {
                new()
                {
                    Text = "- Odaberite -",
                    Value = ""
                }
            };

            var students = await _studentRepository.GetAll();

            if (userClass != null)
            {
                var studentsToErase = userClass.Students.Select(classStudent => classStudent.Student);
                students = students.Except(studentsToErase);
            }

            selectItems.AddRange(students.Select(student => new SelectListItem
            {
                Text = student.FullName,
                Value = student.StudentId.ToString()
            }));

            ViewBag.PossibleStudents = selectItems;
        }

        [HttpPost]
        public async Task<IActionResult> ApplyEditToClass(Guid classId, string studentsToEditJson)
        {
            var classToUpdate = await _classRepository.GetClass(classId);

            if (!string.IsNullOrEmpty(studentsToEditJson))
            {
                var studentIdsToEdit = JsonSerializer.Deserialize<Guid[]>(studentsToEditJson);
                var studentsToEdit = (await _studentRepository.GetAll())
                    .Where(student => studentIdsToEdit.Contains(student.StudentId));

                foreach (var student in studentsToEdit)
                {
                    if (classToUpdate.Students.Any(p => p.StudentId == student.StudentId))
                    {
                        var toDelete = classToUpdate.Students.First(p => p.StudentId == student.StudentId);
                        classToUpdate.Students.Remove(toDelete);
                    }
                    else
                    {
                        classToUpdate.Students.Add(new ClassStudent
                        {
                            ClassStudentId = new Guid(),
                            StudentId = student.StudentId,
                            Student = student,
                            ClassId = classToUpdate.ClassId,
                            Class = classToUpdate,
                            EnrollDate = DateTime.Now,
                            Pass = 0
                        });
                    }
                }
            }

            var updateSuccess = await TryUpdateModelAsync(classToUpdate);
            if (updateSuccess && ModelState.IsValid)
                await _classRepository.SaveChanges();

            return RedirectToAction("Index", new {professorId = classToUpdate.ProfessorId});
        }

        [HttpPost]
        public async Task<IActionResult> AddClassPost(Class model, string studentsToEditJson)
        {
            model.ClassId = Guid.NewGuid();

            await _classRepository.AddClass(model);

            var classToUpdate = await _classRepository.GetClass(model.ClassId);

            if (!string.IsNullOrEmpty(studentsToEditJson))
            {
                var studentIdsToEdit = JsonSerializer.Deserialize<Guid[]>(studentsToEditJson);
                var studentsToEdit = (await _studentRepository.GetAll())
                    .Where(student => studentIdsToEdit.Contains(student.StudentId));

                foreach (var student in studentsToEdit)
                {
                    classToUpdate.Students.Add(new ClassStudent
                    {
                        ClassStudentId = new Guid(),
                        StudentId = student.StudentId,
                        Student = student,
                        ClassId = model.ClassId,
                        Class = model,
                        EnrollDate = DateTime.Now,
                        Pass = 0
                    });
                }

                var updateSuccess = await TryUpdateModelAsync(classToUpdate);
                if (updateSuccess && ModelState.IsValid)
                    await _classRepository.SaveChanges();
            }

            return RedirectToAction("Index", new {professorId = model.ProfessorId});
        }

        [HttpGet]
        public IActionResult StudentLink(Guid studentId)
        {
            return PartialView("_StudentLink", studentId);
        }
    }
}

StudentTracker/StudentTracker.Web/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using StudentTracker.Model;
using StudentTracker.Web.Models;
using StudentTracker.Web.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentTracker.Web.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;

        public StudentController(IStudentRepository studentRepository)
        {
            _studentRepository = studentRepository;
        }

        [HttpGet("student/index")]
        public async Task<IActionResult> Index(StudentFilterModel filter)
        {
            IEnumerable<Student> studentQuery = await _studentRepository.GetAll();

            filter = filter ?? new StudentFilterModel();

            if (!string.IsNullOrWhiteSpace(filter.FullName))
                studentQuery = studentQuery.Where(p => (p.FullName).ToLower().Contains(filter.FullName.ToLower()));

            if (!string.IsNullOrWhiteSpace(filter.Address))
                studentQuery = studentQuery.Where(p => p.Address.ToLower().Contains(filter.Address.ToLower()));

            if (!string.IsNullOrWhiteSpace(filter.Phone))
                studentQuery = studentQuery.Where(p => p.Phone.ToLower().Contains(filter.Phone.ToLower()));

            if (!string.IsNullOrWhiteSpace(filter.Jmbag))
                studentQuery = studentQuery.Where(p => p.Jmbag.ToLower().Contains(filter.Jmbag.ToLower()));
          
            List<Student> model = studentQuery.ToList();
            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> IndexFilter(StudentFilterModel filter)
        {
            IEnumerable<Student> studentQuery = await _studentRepository.GetAll();

            filter = filter ?? new StudentFilterModel();

            if (!string.IsNullOrWhiteSpace(filter.FullName))
                studentQuery = studentQuery.Where(p => (p.FullName).ToLower().Contains(filter.FullName.ToLower()));

            if (!string.IsNullOrWhiteSpace(filter.Address))
                studentQuery = studentQuery.Where(p => p.Address.ToLower().Contains(filter.Address.ToLower()));

            if (!string.IsNullOrWhiteSpace(filter.Phone))
                studentQuery = studentQuery.Where(p => p.Phone.ToLower().Contains(filter.Phone.ToLower()));

            if (!string.IsNullOrWhiteSpace(filter.Jmbag))
                studentQuery = studentQuery.Where(p => p.Jmbag.ToLower().Contains(filter.Jmbag.ToLower()));

            List<Student> model = studentQuery.ToList();
            return PartialView("_IndexTable", model);
        }

        [HttpGet("student/create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Student model)
        {
            if (ModelState.IsValid)
            {
                await _studentRepository.Add(model);
                await _studentRepository.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        [HttpGet("student/edit")]
        public async Task<IActionResult> Edit(Guid id)
        {
            Student model = await _studentRepository.GetStudent(id);

            return View(model);
        }

        [HttpPost]
        [ActionName(nameof(Edit))]
        public async Task<IActionResult> EditPost(Guid studentId)
        {
            Student model = await _studentRepository.GetStudent(studentId);
            var ok = await TryUpdateModelAsync(model);

            if (ok && this.ModelState.IsValid)
            {
                await _studentRepository.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet("student/details")]
        public async Task<IActionResult> Details(Guid studentId)
        {
            var studentProfile = await _studentRepository.GetStudent(studentId);

            if (studentProfile != null)
            {
                return View(studentProfile);
            }

            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var studentToDelete = await _studentRepository.GetStudent(id);

            if (studentToDelete != null)
            {
                await _studentRepository.Remove(studentToDelete);

                return RedirectToAction("Index");
            }

            return NotFound();

        }
    }
}

StudentTracker/StudentTracker.Web/Views/Class/AddClass.cshtml
@model StudentTracker.Model.Class

<h4>Add class</h4>
<hr/>

<div class="row">
    <div class="col-6">
        <form asp-action="AddClassPost" method="post">
            <partial name="_CreateOrEdit"/>
        </form>
    </div>

    <div class="col-4">
        <h4>Students in the class</h4>
        <table id="myTable" class="table table-hover table-striped">
            <tbody></tbody>
        </table>
    </div>
</div>

@section Scripts
{
    <script>
        let students_to_edit = [];

        /*when user selects a student from the dropdown,
         * add him to the applied student table and add him to
         * an array which goes to the backend for db add
        */
        $('#addingSelect').on('change', function (e) {
            if (!students_to_edit.includes($(this).find("option:selected").val())) {
                students_to_edit.push($(this).find("option:selected").val())
            } else {
                students_to_edit.splice(students_to_edit.indexOf($(this).find("option:selected").val()), 1)
            }

            $('#myTable > tbody:last-child').append("<tr><td>" + $(this).find("option:selected").text() + "</td><td><button id='remove' type='button' value='" + $(this).find("option:selected").val() + "'class='btn btn-danger'>Remove student</button>");
            $(this).find("option:selected").remove()
        })

        /*when user deletes a student from the table,
         * add him to the array and delete on the backend
        */
        $('tbody').on("click", "[id = remove]",function () {
            $("#addingSelect").append($('<option/>', {
                value: $(this).val(),
                text: $(this).parent().closest("tr").children().first().text()
            }))
            students_to_edit.push($(this).val())
            $(this).closest("tr").remove()
        })

        $("form").submit(function () {
            $("#studentsToEditJson").val(JSON.stringify(students_to_edit));
        })
    </script>
}

StudentTracker/StudentTracker.Web/Views/Class/EditClass.cshtml
@model StudentTracker.Model.Class

<h4>Edit class</h4>
<hr/>
<div class="row">
    <div class="col-6">
        <form asp-action="ApplyEditToClass" method="post">
            <partial name="_CreateOrEdit"/>
        </form>
    </div>

    <div class="col-4">
        <h4>Students in the class</h4>
        <table id="myTable" class="table table-hover table-striped">
            <tbody>
            @foreach (var item in Model.Students)
            {
                <tr>
                    <td id="name">
                        <a asp-controller="Student" asp-action="Details" asp-route-studentId="@item.StudentId">@item.Student.FullName</a>
                    </td>
                    <td>
                        <button id="remove" type="button" value="@item.Student.StudentId" class="btn btn-danger">Remove student</button>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    <script >
        let students_to_edit = [];

        /*when user selects a student from the dropdown,
         * add him to the applied student table and add him to
         * an array which goes to the backend for db add
        */
        $('#addingSelect').on('change', function (e) {
            if (!students_to_edit.includes($(this).find("option:selected").val())) {
                students_to_edit.push($(this).find("option:selected").val())
            } else {
                students_to_edit.splice(students_to_edit.indexOf($(this).find("option:selected").val()), 1)
            }

            //Ajax gets the partial view with a tag helper generated link and inserts it into the table
            $.ajax({
                type: "GET",
                url: '@Url.Action("StudentLink", "Class")',
                data: { studentId : $(this).find("option:selected").val() },
                success: function (html) {
                    $('#myTable > tbody:last-child').append("<tr><td>" + html + "</td><td><button id='remove' type='button' value='" + $('#addingSelect').find("option:selected").val() + "'class='btn btn-danger'>Remove student</button>")
                    $('#myTable tr:last-child td:first-child a').text($('#addingSelect').find("option:selected").text())
                    $('#addingSelect').find("option:selected").remove()
                }
            })
        })

        /*when user deletes a student from the table,
         * add him to the array and delete on the backend
        */
        $('tbody').on("click", "[id = remove]",function () {
            $("#addingSelect").append($('<option/>', {
                value: $(this).val(),
                text: $(this).parent().closest("tr").children().first().text()
            }))

            if (!students_to_edit.includes($(this).val())) {
                students_to_edit.push($(this).val())
            } else {
                students_to_edit.splice(students_to_edit.indexOf($(this).val()), 1)
            }

            $(this).closest("tr").remove()
        })

        $("form").submit(function () {
            $("#studentsToEditJson").val(JSON.stringify(students_to_edit));
        })
    </script >
}

StudentTracker/StudentTracker.Web/Views/Class/Index.cshtml
@model List<StudentTracker.Model.Class>

<h4>Your classes</h4>
<hr/>

<div class="container">
    <div class="row justify-content-start">
        <div class="col-4 mb-3">
            <div class="card h-100 border-primary mb-3">
                <div class="card-body text-dark align-items-center justify-content-center d-flex">
                    <div style="min-width:80%">
                        <a class="btn btn-primary" asp-controller="Class" asp-action="AddClass" asp-route-professorId="@ViewBag.professorId" role="button" style="width:100%">Add class</a>
                    </div>
                </div>
            </div>
        </div>
        @foreach (var item in Model)
        {
            <div class="col-4 mb-3">
                <div class="card h-100 border-primary mb-3">
                    <h6 class="card-header bg-transparent border-primary">@item.Name</h6>
                    <div class="card-body text-dark">
                        <p class="card-title">Semester: @item.Semester.</p>
                        @if (item.Students != null && item.Students.Any())
                        {
                            <p class="card-title">Number of students: @item.Students.Count()</p>
                        }
                        else
                        {
                            <p class="card-title">Number of students: 0</p>
                        }

                        @if (item.Terms != null && item.Terms.Any())
                        {
                            <p class="card-title">Number of terms: @item.Terms.Count()</p>
                        }
                        else
                        {
                            <p class="card-title mb-0">Number of terms: 0</p>
                        }
                    </div>
                    <div class="card-footer bg-transparent border-primary">
                        <a class="btn btn-primary" asp-controller="Class" asp-action="EditClass" asp-route-classId="@item.ClassId" role="button">Edit class</a>

                        <a class="btn btn-danger" asp-controller="Class" asp-action="DeleteClass" asp-route-classId="@item.ClassId" role="button">Delete class</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

StudentTracker/StudentTracker.Web/Views/Class/_ClassFilter.cshtml
@model string

<form action="@Url.Action("FilterClass")" method="post">
    <div class="form-row">
        <div class="col-3">
            <input class="form-control" type="text" placeholder="Class name"/>
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-outline-info">Filter</button>
        </div>
    </div>
</form>

StudentTracker/StudentTracker.Web/Views/Class/_CreateOrEdit.cshtml
@model StudentTracker.Model.Class

<div class="form-group">
    <label class="control-label">Name</label>
    <input asp-for="Name" class="form-control"/>
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label class="control-label">Semester</label>
    <select class="form-select form-control" asp-for="Semester">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
    </select>
    <span asp-validation-for="Semester" class="text-danger"></span>
</div>
<div class="form-group">
    <label class="control-label" for="addingSelect">Add Students</label>
    <select class="form-control" id="addingSelect" asp-items="ViewBag.PossibleStudents"></select>
</div>
<input type="hidden" id="studentsToEditJson" name="studentsToEditJson"/>
@if (Model != null)
{
    <input type="hidden" id="classId" name="classId" value="@Model.ClassId"/>
}
else
{
    <input type="hidden" asp-for="ProfessorId" value="@ViewBag.professorId"/>
}

<button type="submit" class="btn btn-outline-info">Save changes</button>

StudentTracker/StudentTracker.Web/Views/Class/_StudentLink.cshtml
@model Guid

<a asp-controller="Student" asp-action="Details" asp-route-studentId="@Model"></a>